# Basic test set
[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-master.txt"]
skips = ["install/freedreno-a618-premerge-skips.txt"]
renderer_check = "Turnip Adreno .* 618"
fraction = 2

# force-gmem testing
# Autotuner forces sysmem on most CTS tests
[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-master.txt"]
skips = ["install/freedreno-a618-premerge-skips.txt"]
prefix = "gmem-"
fraction = 15
[deqp.env]
TU_DEBUG = "gmem,forcebin"

[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-master.txt"]
skips = ["install/freedreno-a618-premerge-skips.txt"]
include = ["dEQP-VK.graphicsfuzz.*", "dEQP-VK.subgroups.ballot*"]
prefix = "spill-"
[deqp.env]
IR3_SHADER_DEBUG = "spillall"
