# Basic test set
[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-master.txt"]
skips = ["install/freedreno-a660-premerge-skips.txt"]
renderer_check = "Turnip Adreno .* 660"
fraction = 2

# force-gmem testing
# Autotuner forces sysmem on most CTS tests
[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-master.txt"]
skips = ["install/freedreno-a660-premerge-skips.txt"]
prefix = "gmem-"
fraction = 15
[deqp.env]
TU_DEBUG = "gmem,forcebin"

# spillall and stale regs testing disabled due to crashing a ton.
#[[deqp]]
#deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
#caselists = ["/deqp/mustpass/vk-master.txt"]
#skips = ["install/freedreno-a660-premerge-skips.txt"]
#include = ["dEQP-VK.graphicsfuzz.*", "dEQP-VK.subgroups.ballot*"]
#prefix = "spill-"
#[deqp.env]
#IR3_SHADER_DEBUG = "spillall"

# testing for stale regs usage
#[[deqp]]
#deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
#caselists = ["/deqp/mustpass/vk-master.txt"]
#skips = ["install/freedreno-a660-premerge-skips.txt"]
#prefix = "stale-regs-"
#fraction = 200
#[deqp.env]
#TU_DEBUG = "gmem,forcebin"
#TU_DEBUG_STALE_REGS_RANGE = "0x0c00,0xbe01"
#TU_DEBUG_STALE_REGS_FLAGS = "cmdbuf,renderpass"
