# x11
[[deqp]]
deqp = "/deqp/modules/egl/deqp-egl-x11"
caselists = ["/deqp/mustpass/egl-master.txt"]
skips = ["install/freedreno-a618-premerge-skips.txt"]
deqp_args = [
    "--deqp-surface-width=256", "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer", "--deqp-visibility=hidden",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
]

[[deqp]]
deqp = "/deqp/modules/egl/deqp-egl-wayland"
caselists = ["/deqp/mustpass/egl-master.txt"]
skips = ["install/freedreno-a618-premerge-skips.txt"]
deqp_args = [
    "--deqp-surface-width=256", "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer", "--deqp-visibility=hidden",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
]
prefix = "wayland-"
