[[deqp]]
deqp = "/deqp/modules/gles2/deqp-gles2"
caselists = ["/deqp/mustpass/gles2-master.txt"]
tests_per_group = 250
deqp_args = [
    "--deqp-surface-width=256", "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer", "--deqp-visibility=hidden",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
]
version_check = "GL ES 2.0.*git"
renderer_check = "Mali450"

# wayland
[[deqp]]
deqp = "/deqp/modules/egl/deqp-egl-wayland"
caselists = ["/deqp/mustpass/egl-master.txt"]
tests_per_group = 250
deqp_args = [
    "--deqp-surface-width=256", "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer", "--deqp-visibility=hidden",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
]
prefix = "wayland-"

# x11
[[deqp]]
deqp = "/deqp/modules/egl/deqp-egl-x11"
caselists = ["/deqp/mustpass/egl-master.txt"]
tests_per_group = 250
deqp_args = [
    "--deqp-surface-width=256", "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer", "--deqp-visibility=hidden",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
]
prefix = "x11-"
