[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = [ "/deqp/mustpass/vk-master.txt" ]
timeout = 30.0 # Starting lots of Crosvm instances simultaneously can take some time
renderer_check = "Virtio-GPU Venus.*llvmpipe"
