[[deqp]]
deqp = "/deqp/external/openglcts/modules/glcts"
caselists = [
    "/deqp/mustpass/gles2-master.txt",
    "/deqp/mustpass/gles3-master.txt",
    "/deqp/mustpass/gles31-master.txt",
    "/deqp/mustpass/gl46-master.txt",
]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
timeout = 180.0
renderer_check = "zink.*RADV"

[[piglit]]
piglit_folder = "/piglit"
profile = "gpu"
process_isolation = true
timeout = 180.0
  [piglit.env]
  PIGLIT_NO_WINDOW = "1"
  PIGLIT_PLATFORM = "gbm"
  WAFFLE_PLATFORM = "gbm"
