
[[deqp]]
deqp = "/deqp/modules/gles31/deqp-gles31"
caselists = ["/deqp/mustpass/gles31-master.txt"]
skips = ["install/llvmpipe-skips.txt"]
deqp_args = [
    "--deqp-surface-width=256", "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer", "--deqp-gl-config-name=rgba8888d24s8ms0", "--deqp-visibility=hidden"
]
fraction = 10
version_check = "GL ES 3.2.*git"
renderer_check = "llvmpipe"
  [deqp.env]
  LD_PRELOAD = "libasan.so.8"
