[[deqp]]
deqp = "/install/crosvm-runner.sh"
caselists = ["/deqp/mustpass/gles2-master.txt"]
deqp_args = [
    "/deqp/modules/gles2/deqp-gles2",
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
timeout = 360.0 # Starting 8 Crosvm instances simultaneously can take some time
version_check = "GL ES 3.2.*git"
renderer_check = "virgl.*LLVMPIPE"

[[deqp]]
deqp = "/install/crosvm-runner.sh"
caselists = ["/deqp/mustpass/gles3-master.txt"]
deqp_args = [
    "/deqp/modules/gles3/deqp-gles3",
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
timeout = 360.0 # Starting 8 Crosvm instances simultaneously can take some time

[[deqp]]
deqp = "/install/crosvm-runner.sh"
caselists = ["/deqp/mustpass/gles31-master.txt"]
deqp_args = [
    "/deqp/modules/gles31/deqp-gles31",
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
timeout = 360.0 # Starting 8 Crosvm instances simultaneously can take some time

[[deqp]]
deqp = "/install/crosvm-runner.sh"
caselists = [
    "/deqp/mustpass/gl32-master.txt",
]
deqp_args = [
    "/deqp/external/openglcts/modules/glcts",
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
timeout = 360.0 # Starting 8 Crosvm instances simultaneously can take some time
