include:
  - local: 'src/gallium/drivers/nouveau/ci/gitlab-ci-inc.yml'

# 6 Jetson TK1 boards at anholt's house.
gk20a-gles:
  extends:
    - .gk20a-test
  parallel: 4
  timeout: 30m
  variables:
    HWCI_TEST_SCRIPT: "/install/deqp-runner.sh"
    DEQP_SUITE: nouveau-gk20a
    FARM : anholt
    DEVICE_TYPE: anholt-jetson
